# Generated by Django 3.0.4 on 2020-03-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
