# Generated by Django 3.0.4 on 2020-03-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_comment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
